on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        
    - run: |
        aws deploy create-deployment \
        --application-name my-application \
        --deployment-group-name depgrp3 \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --file-exists-behavior OVERWRITE \
        --github-location repository=${{ github.repository }},commitId=${{ github.sha }}

